name: bolgram_forwarder
description: بولگرام، اپ ارسال پیامک بانکی برای تطبیق خودکار واریزهای کارت‌به‌کارت.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  # QR scanner for pairing
  mobile_scanner: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
